# Get names of survived people

In [1]:
import numpy as np
import pandas as pd
from os import path
import regex
import re

Now let's try to match the names of survived people (from https://www.encyclopedia-titanica.org/titanic-survivors/) and the names from data set. First let's get the names of survived people.

In [2]:
survived_data_dir = './special_data'
raw_survived = ''
with open(path.join(survived_data_dir, 'encyclopedia-titanica.html'), 'r', encoding='UTF-8') as f:
    raw_survived = f.read()

In [3]:
last_names = regex.findall('<span itemprop="familyName">.*\,', raw_survived)
last_names = [str.replace(last_name, '<span itemprop="familyName">', '') for last_name in last_names]
last_names = [str.replace(last_name, '</span>,', '').capitalize() for last_name in last_names]
first_names = regex.findall('<span itemprop="givenName">.*<\/span>', raw_survived)
first_names = [str.replace(first_name, '<span itemprop="givenName">', '') for first_name in first_names]
first_names = [str.replace(first_name, '</span>', '') for first_name in first_names]
titles = regex.findall('<span itemprop="honorificPrefix">.*<\/span>', raw_survived)
titles = [str.replace(title, '<span itemprop="honorificPrefix">', '') for title in titles]
titles = [str.replace(title, '</span>', '') for title in titles]

titles_firsts = [' '.join(title_first) for title_first in zip(titles, first_names)]
names = [', '.join(first_last) for first_last in zip(last_names, titles_firsts)]
names

["Abbott, Mrs Rhoda Mary 'Rosa'",
 'Abelseth, Miss Kalle (Karen) Marie Kristiane',
 'Abelseth, Mr Olaus Jørgensen',
 'Abelson, Mrs Anna',
 "Abī sa'b, Mrs Sha'nīnah",
 'Abī-al-munà, Mr Nāsīf Qāsim',
 'Abrahamsson, Mr August Abraham Johannes',
 'Aks, Mrs Leah',
 'Aks, Master Philip',
 "Al-ba'qlīnī, Mrs Laṭīfah",
 "Al-ba'qlīnī, Miss Mārīyā",
 "Al-ba'qlīnī, Miss Ūwjīnīyā",
 "Al-ba'qlīnī, Miss Hilānah",
 "Al-za'innī, Mr Fahīm Rūḥānā",
 'Allen, Miss Elisabeth Walton',
 'Allen, Mr Ernest Frederick',
 'Allison, Master Hudson Trevor',
 'Andersen (jensen), Miss Carla Christine Nielsine',
 'Anderson, Mr Harry',
 'Anderson, Mr John',
 'Andersson, Miss Erna Alexandra',
 'Andrews, Miss Cornelia Theodosia',
 'Andrews, Mr Charles Edward',
 'Angle, Mrs Florence Agnes',
 'Appleton, Mrs Charlotte',
 'Archer, Mr Ernest Edward',
 'Asplund, Master Edvin Rojj Felix',
 'Asplund, Mr Johan Charles',
 'Asplund, Mrs Selma Augusta Emilia',
 'Asplund, Miss Lillian Gertrud',
 'Astor, Mrs Madeleine Talmage',
 'Aubart, Mme. Léontine Pauline',
 'Avery, Mr James Albert',
 'Ayyūb-dāhir, Miss Bannūrah',
 'Backström, Mrs Maria Mathilda',
 'Badman, Miss Emily Louisa',
 'Baggott, Mr Allen Marden',
 'Bailey, Mr Henry Joseph',
 'Ball, Mr Percy',
 'Balls, Mrs Ada Elizabeth',
 'Barber, Miss Ellen Mary',
 'Barkworth, Mr Algernon Henry',
 'Barrett, Mr Frederick William',
 'Bassani, Mrs Albina',
 'Baxter, Mrs Hélène',
 'Beane, Mr Edward',
 'Beane, Mrs Ethel Louisa',
 'Beauchamp, Mr George William',
 'Becker, Mrs Nellie E.',
 'Becker, Miss Marion Louise',
 'Becker, Master Richard F.',
 'Becker, Miss Ruth Elizabeth',
 'Beckwith, Mr Richard Leonard',
 'Beckwith, Mrs Sarah Maybell',
 'Beesley, Mr Lawrence',
 'Behr, Mr Karl Howell',
 'Bennett, Mrs Mabel Kate',
 'Bentham, Miss Lillian Winifred',
 'Bessette, Miss Nellie Mayo',
 'Bidois, Miss Rosalie',
 'Bing, Mr Lee',
 'Binstead, Mr Walter William',
 'Bird, Miss Ellen',
 'Bishop, Mr Dickinson H.',
 'Bishop, Mrs Helen Margaret',
 'Björnström-steffansson, Mr Mauritz Håkan',
 'Blake, Mr Percival Albert',
 'Blank, Mr Henry',
 'Bliss, Mrs Emma',
 'Bonnell, Miss Caroline',
 'Bonnell, Miss Elizabeth',
 'Bowen, Miss Grace Scott',
 'Bowerman, Miss Elsie Edith',
 'Bowker, Miss Ruth Harwood',
 'Boxhall, Mr Joseph Groves',
 'Bradley, Miss Bridget',
 'Brereton, Mr George Andrew',
 'Brice, Mr Walter Thomas',
 'Bride, Mr Harold Sydney',
 'Bright, Mr Arthur John',
 'Brown, Miss Amelia Mary',
 'Brown, Mrs Caroline Lane',
 'Brown, Mrs Margaret',
 'Brown, Mrs Elizabeth Catherine',
 'Brown, Miss Edith Eileen',
 'Brown, Mr Edward',
 'Bryhl, Miss Dagmar Jenny Ingeborg',
 'Buckley, Mr Daniel',
 'Bucknell, Mrs Emma Eliza',
 'Buley, Mr Edward John',
 'Burgess, Mr Charles',
 'Burke, Mr William',
 'Burns, Miss Elizabeth Margaret',
 'Burrage, Mr Arthur Victor Edwards',
 'Buss, Miss Kate',
 'Byström, Mrs Karolina',
 'Calderhead, Mr Edward Pennington',
 'Caldwell, Mr Albert Francis',
 'Caldwell, Mrs Sylvia Mae',
 'Caldwell, Master Alden Gates',
 'Cameron, Miss Clear Annie',
 'Candee, Mrs Helen Churchill',
 'Cardeza, Mrs Charlotte Wardle',
 'Cardeza, Mr Thomas Drake Martinez',
 'Carter, Mr William Ernest',
 'Carter, Mrs Lucile',
 'Carter, Miss Lucile Polk',
 'Carter, Master William Thornton II',
 'Cassebeer, Mrs Eleanor Genevieve',
 'Caton, Miss Annie',
 'Cavell, Mr George Henry',
 'Cavendish, Mrs Julia Florence',
 'Chaffee, Mrs Carrie Constance',
 'Chambers, Mr Norman Campbell',
 'Chambers, Mrs Bertha',
 'Chapman, Mr Joseph Charles',
 'Chaudanson, Miss Victorine',
 'Cherry, Miss Gladys',
 'Chevré, Mr Paul Romaine Marie Léonce',
 'Chibnall, Mrs Edith Martha Bowerman',
 'Chip, Mr Chang',
 'Christy, Mrs Alice Frances',
 'Christy, Miss Rachel Juli Cohen',
 'Clark, Mrs Virginia Estelle',
 'Clark, Mr William',
 'Clarke, Mrs Ada Maria',
 'Cleaver, Miss Alice Catherine',
 'Clench, Mr Frederick Charles',
 'Cohen, Mr Gurshon',
 'Colgan, Mr Joseph',
 'Collett, Mr Sidney Clarence Stuart',
 'Collins, Mr John',
 'Collins, Mr John',
 'Collyer, Mrs Charlotte Caroline',
 'Collyer, Miss Marjorie Lottie',
 'Combes, Mr George',
 'Compton, Mrs Mary Eliza',
 'Compton, Miss Sara Rebecca',
 'Connolly, Miss Catherine',
 'Cook, Mrs Selena',
 'Cornell, Mrs Malvina Helen',
 'Corr, Miss Ellen',
 'Couper, Mr Robert Frederick William',
 'Coutts, Mrs Minnie',
 'Coutts, Master William Loch',
 'Coutts, Master Neville Leslie',
 'Crafter, Mr Frederick Horace',
 'Crawford, Mr Alfred George',
 'Cribb, Miss Laura May',
 'Crimmins, Mr James',
 'Crosby, Mrs Catherine Elizabeth',
 'Crosby, Miss Harriette Rebecca',
 'Crow, Mr George Frederick',
 'Cullen, Mr Charles James',
 'Cumings, Mrs Florence Briggs',
 'Cunningham, Mr Andrew Orr',
 'Dahl, Mr Charles Edward',
 'Daly, Mr Peter Dennis',
 'Daly, Miss Margaret',
 'Daly, Mr Eugene Patrick',
 'Daniel, Mr Robert Williams',
 'Daniels, Miss Sarah Rebecca',
 'Daniels, Mr Sidney Edward',
 'Davidson, Mrs Orian',
 'Davies, Mrs Agnes',
 'Davies, Master John Morgan jr',
 'Davis, Miss Mary Ann Charlotte',
 'Davison, Mrs Mary Elizabeth',
 'De messemaeker, Mr Guillaume Joseph',
 'De messemaeker, Mrs Anna',
 'De mulder, Mr Theodoor',
 'Dean, Mrs Eva Georgetta',
 'Dean, Master Bertram Vere',
 'Dean, Miss Eliza Gladys Millvina',
 'Del carlo, Mrs Argene',
 'Devaney, Miss Margaret Bedelia',
 'Diaper, Mr John Joseph',
 'Dick, Mr Albert Adrian',
 'Dick, Mrs Vera',
 'Dillon, Mr Thomas Patrick',
 'Dodge, Dr Washington',
 'Dodge, Mrs Ruth',
 'Dodge, Master Washington',
 'Doel, Mr Frederick',
 'Doling, Mrs Ada Julia Elizabeth',
 'Doling, Miss Elsie',
 'Dore, Mr Albert James',
 'Dorkings, Mr Edward Arthur',
 'Douglas, Mrs Mahala',
 'Douglas, Mrs Mary Hélène',
 'Dowdell, Miss Elizabeth',
 'Drew, Mrs Maria Louisa Thorne',
 'Drew, Master Marshall Brines',
 'Driscoll, Miss Bridget',
 'Dropkin, Miss Jennie',
 'Duff gordon, Sir Cosmo Edmund',
 'Duff gordon, Mr Lucy Christiana, Lady',
 'Duquemin, Miss Joseph Pierre',
 'Durán i moné, Miss Florentina',
 'Durán i moné, Mrs Asuncion',
 'Dyker, Mr Anna Elisabeth Judith',
 'Dymond, Mrs Frank',
 'Earnshaw, Mr Olive',
 'Ellis, Miss John Bertie',
 'Emanuel, Miss Virginia Ethel',
 'Endres, Mr Caroline Louise',
 'Etches, Miss Henry Samuel',
 'Eustis, Mr Elizabeth Mussey',
 'Evans, Mr Alfred Frank',
 'Evans, Mr Frank Oliver',
 'Faulkner, Mr William Stephen',
 'Finoli, Mr Luigi',
 'Fitzpatrick, Mr Cecil William',
 'Flaherty, Mr Edward',
 'Fleet, Mrs Frederick',
 'Flegenheim, Miss Antoinette',
 'Fleming, Mr Margaret',
 'Flynn, Mr John Irwin',
 'Foley, Mr John',
 'Foley, Mr Wilfred Cyril',
 'Foo, Mrs Choong',
 'Fortune, Miss Mary',
 'Fortune, Miss Ethel Flora',
 'Fortune, Miss Alice Elizabeth',
 'Fortune, Mr Mabel Helen',
 'Forward, Miss James',
 'Francatelli, Mr Laura Mabel',
 'Frauenthal, Dr Isaac Gerry',
 'Frauenthal, Mrs Henry William',
 'Frauenthal, Mr Clara',
 'Fredericks, Miss Walter Francis',
 'Frölicher, Mr Hedwig Margaritha',
 'Frölicher-stehli, Mrs Maximilian Josef',
 'Frölicher-stehli, Mr Margaretha Emerentia',
 'Fryer, Mrs Albert Ernest',
 'Futrelle, Miss Lily May',
 'Garside, Mr Ethel',
 'Gibbons, Mrs Jacob William',
 'Gibson, Miss Pauline Caroline',
 'Gibson, Miss Dorothy Winifred',
 'Gieger, Miss Amalie Henriette',
 'Gilnagh, Miss Kate',
 'Glynn, Mr Mary Agatha',
 'Godley, Mrs George Auguste',
 'Gold, Mr Jane Kate Coulson',
 'Goldenberg, Mrs Samuel Levi',
 'Goldenberg, Mrs Nella Carlynne',
 'Goldsmith, Master Emily Alice',
 'Goldsmith, Colonel Frank John William',
 'Gracie, Mrs Archibald',
 'Graham, Miss Edith',
 'Graham, Mr Margaret Edith',
 'Graham, Mrs Thomas Gibson',
 'Greenfield, Mr Blanche',
 'Greenfield, Miss William Bertram',
 'Gregson, Mr Mary Josephine',
 'Guy, Mr Elgar John',
 'Haggan, Mr John',
 'Haines, Mrs Albert',
 'Hakkarainen, Mr Elin Matilda',
 'Halford, Mrs Richard',
 'Hämäläinen, Master Anna Lydia Amanda',
 'Hämäläinen, Mr Viljo Unto Johannes',
 'Ḥannā, Mrs Mubārik Sulaymān Abī Āsī',
 'Hansen, Mr Jennie Louise',
 'Harder, Mrs George Achilles',
 'Harder, Mr Dorothy',
 'Harder, Mr William',
 'Hardwick, Mr Reginald',
 'Hardy, Mr John',
 'Harper, Mrs Henry Sleeper',
 'Harper, Miss Myra Raymond',
 'Harper, Mrs Annie Jessie',
 'Harris, Mr Irene',
 'Harris, Mr George',
 'Harris, Mr Fred',
 'Harrison, Mrs Aragõa Drummond',
 'Hart, Miss Emily Esther Louisa',
 'Hart, Mr Eva Miriam',
 'Hart, Mr John Edward',
 'Hartnell, Mr Fred',
 'Hassab, Mr Hammad',
 'Hawksford, Mrs Walter James',
 'Hays, Miss Clara Jennings',
 'Hays, Miss Margaret Bechstein',
 'Healy, Mr Honor',
 'Hebb, Mr William Albert Thomas',
 'Hedman, Mr Oskar Arvid',
 'Hee, Miss Ling',
 'Heikkinen, Miss Laina Maria',
 'Hellström, Mr Hilda Maria',
 'Hemming, Mr Samuel Ernest',
 'Hendrickson, Mrs Charles Osker',
 'Herman, Miss Jane',
 'Herman, Miss Alice',
 'Herman, Mrs Kate',
 'Hewlett, Mr Mary Dunbar',
 'Hichens, Mrs Robert',
 'Hippach, Miss Ida Sophia',
 'Hippach, Mrs Gertrude Isabelle',
 'Hirvonen, Miss Helga Elisabeth Lindqvist',
 'Hirvonen, Mrs Hildur Elisabeth',
 'Hocking, Miss Eliza',
 'Hocking, Mrs Ellen',
 'Hogeboom, Mr Anna Louisa',
 'Hogg, Mrs George Alfred',
 'Hold, Mrs Annie Margaret',
 'Holverson, Mr Mary Alice',
 'Homer, Miss Harry Haven',
 'Honkanen, Mr Eliina',
 'Hopkins, Mr Robert John',
 'Horswill, Mr Albert Edward James',
 'Hosono, Miss Masabumi',
 'Howard, Mr May Elizabeth',
 'Hoyt, Mrs Frederick Maxfield',
 'Hoyt, Mr Jane Anne',
 'Humphreys, Mr Sidney',
 'Hunt, Mr Albert Sylvanus',
 'Hurst, Mr Walter',
 'Hyland, Mr Leo James',
 'Hyman, Mrs Joseph Abraham',
 'Ibrāhīm, Miss Sāfiyah',
 'Icard, Miss Rose Amélie',
 'Ilett, Mr Bertha',
 'Ismay, Mrs Joseph Bruce',
 'Jacobsohn, Mr Amy Frances Christy',
 'Jalševac, Mr Ivan',
 'Jansson, Miss Carl Olof',
 'Jermyn, Mrs Annie Jane',
 'Jerwan, Miss Marie Marthe',
 'Jessop, Mr Violet Constance',
 'Jewell, Mr Archie',
 'Johannesen, Mr Bernt Johannes',
 'Johansson, Mrs Oscar Wilhelm',
 'Johnson, Master Aliina Vilhelmina',
 'Johnson, Miss Harold Theodor',
 'Johnson, Mr Eleanor Ileen',
 'Johnstone, Mr James',
 'Jones, Mr Thomas William',
 'Jonsson, Mr Karl',
 'Joughin, Mr Charles John',
 'Judd, Mr Charles Edward',
 'Jussila, Mrs Eiriik',
 'Kantor, Mr Miriam',
 'Karlsson, Mr Einar Gervasius',
 'Karun, Miss Franz',
 'Karun, Mr Manca',
 'Kasper, Miss F.',
 'Keane, Mr Nora Agnes',
 'Keen, Mrs Percy Edward',
 'Kelly, Miss Fanny Maria',
 'Kelly, Miss Anna Katherine',
 'Kelly, Mr Mary',
 'Kemish, Mr George',
 'Kennedy, Mrs John',
 'Kenyon, Mr Marion Estelle',
 'Kimball, Mrs Edwin Nelson Jr.',
 'Kimball, Mr Susan Gertrude',
 'Kink, Mrs Anton',
 'Kink-heilmann, Miss Luise',
 'Kink-heilmann, Mr Luise Gretchen',
 'Knight, Mr George',
 'Knowles, Mr Thomas',
 'Krekorian, Miss Neshan',
 'Kreuchen, Mr Emilie',
 'Lam, Miss Ah',
 'Landergren, Mr Aurora Adelia',
 'Lang, Mrs Fang',
 'Laroche, Miss Juliette Marie Louise',
 'Laroche, Miss Louise',
 'Laroche, Miss Simonne Marie Anne Andrée',
 'Lavington, Dr Elizabeth',
 'Leader, Mrs Alice May',
 'Leather, Mr Elizabeth Mary',
 'Lee, Mr Reginald Robinson',
 'Lee, Miss Henry Reginald',
 'Lehmann, Miss Bertha',
 'Leitch, Mrs Jessie Wills',
 'Lemore, Miss Amelia',
 'Leroy, Mr Berthe',
 'Lesueur, Mr Louis Gustave Joseph',
 'Lewis, Mr Arthur Ernest Read',
 'Lightoller, Mr Charles Herbert',
 'Lindqvist, Mr Eino William',
 'Lindsay, Mrs William Charles',
 'Lindström, Mrs Sigrid',
 'Lines, Miss Elizabeth Lindsey',
 'Lines, Mr Mary Conover',
 'Littlejohn, Miss Alexander James',
 'Longley, Mrs Gretchen Fiske',
 'Louch, Mr Alice Adelaide',
 'Lowe, Mr Harold Godfrey',
 'Lucas, Mr William Arthur',
 'Lucas, Mr William Watson',
 'Lulić, Miss Nikola',
 'Lundin, Mr Olga Elida',
 'Lundström, Miss Thure Edvin',
 'Lurette, Miss Eugénie Elise',
 'Madigan, Miss Margaret',
 'Madill, Mr Georgette Alexandra',
 'Madsen, Miss Fridtjof Arne',
 'Maioni, Mr Roberta Elizabeth Mary',
 'Major, Mrs William James',
 'Mallet, Master Antonine Marie',
 'Mallet, Mr André Clement',
 "Māmā, Miss Hannā Mikā'īl",
 'Mannion, Mr Margaret',
 'Maréchal, Miss Pierre',
 'Marsden, Mrs Evelyn',
 'Martin, Miss Annie Martha',
 'Martin, Mrs Mabel Elvina',
 'Marvin, Mr Mary Graham Carmichael',
 'Mason, Mr Frank Archibald Robert',
 'Maugé, Mr Paul Achille Maurice Germain',
 'Maynard, Mlle Isaac Hiram',
 'Mayné, Mr Berthe Antonine',
 'Mayzes, Miss Thomas Jubilee',
 'Mccarthy, Mr Catherine',
 'Mccarthy, Mr William',
 'Mccormack, Miss Thomas Joseph',
 'Mccoy, Miss Agnes',
 'Mccoy, Mr Alice',
 'Mccoy, Miss Bernard',
 'Mcdermott, Mr Bridget Delia',
 'Mcgann, Mr James',
 'Mcgough, Mr James Robert',
 "Mcgough, Miss George Francis 'Paddy'",
 'Mcgovern, Miss Mary',
 'Mcgowan, Mr Anna Louise',
 'Mcintyre, Mr William',
 'Mckay, Mrs Charles Donald',
 'Mclaren, Mr Hypatia',
 'Mcmicken, Mrs Arthur',
 'Mellinger, Miss Elizabeth Anne',
 'Mellinger, Mr Violet Madeline',
 'Mellors, Mrs William John',
 'Meyer, Mr Leila',
 'Midtsjø, Mr Karl Albert',
 'Mills, Mrs Christopher',
 'Minahan, Miss Lillian Mae',
 'Minahan, Mr Ida Daisy',
 'Mock, Miss Philipp Edmund',
 'Mockler, Mrs Ellen Mary',
 'Moor, Master Beila',
 'Moor, Mr Meier',
 'Moore, Mr George Alfred',
 'Moore, Miss J.',
 'Moran, Mr Bridget (Bertha)',
 'Morris, Mr Frank Herbert',
 'Moss, Mrs Albert Johan',
 'Moussa, Mrs Mantoura Boulos',
 'Mubārik, Master Amīnah',
 'Mubārik, Master Jirjis',
 'Mubārik, Miss Halīm',
 'Mullin, Miss Kate',
 'Mulvihill, Mr Bridget Elizabeth (Bertha)',
 'Murdock, Miss William John',
 'Murphy, Miss Nora',
 'Murphy, Miss Margaret',
 'Murphy, Mrs Kate',
 'Muslamānī, Miss Fatīmah Muhammad',
 'Najīb qiyāmah, Mr Adāl',
 "Nakid, Mrs Sa'īd Antūn",
 "Nakid, Miss Wadi'ah",
 'Nakid, Mrs Mariayam',
 'Naṣr allāh, Mrs Adāl',
 'Naṣr allāh, Master Zād',
 'Navratil, Master Edmond Roger',
 'Navratil, Mr Michel Marcel',
 'Neal, Miss Harold Bentley',
 'Newell, Miss Marjorie Anne',
 'Newell, Miss Madeleine',
 'Newsom, Mr Helen Monypeny',
 'Nichols, Miss Walter Henry',
 'Nilsson, Miss Berta Olivia',
 'Nilsson, Miss Helmina Josefina',
 'Nīqūla yārid, Master Jamīlah',
 'Nīqūla yārid, Mr Ilyās',
 'Niskanen, Mr Juho',
 'Noss, Mr Henry',
 'Nourney, Mr Alfred',
 'Nutbean, Mrs William',
 'Nye, Miss Elizabeth',
 'Nysten, Mrs Anna Sofia',
 "O'brien, Mr Hannah",
 "O'connor, Miss John",
 "O'dwyer, Mr Ellen",
 "O'keeffe, Miss Patrick",
 "O'leary, Miss Hanora",
 'Öhman, Doña Velin Matilda',
 'Oliva y ocana, Mr Fermina',
 'Oliver, Mr Harry',
 'Olliver, Master Alfred John',
 'Olsen, Mr Artur Karl',
 'Omont, Mrs Alfred Fernand',
 'Osman, Mr Mara',
 'Osman, Miss Frank',
 'Ostby, Mr Helen Ragnhild',
 'Othen, Mr Charles Alfred',
 'Oxenham, Mr Percy Thomas',
 'Padron manent, Mr Julian',
 'Pallàs i castelló, Mr Emilio',
 'Palmquist, Mrs Oskar Leander Johansson',
 'Parrish, Mr Lutie Davis',
 'Pascoe, Mr Charles Henry',
 'Pearce, Mr John',
 'Pearcey, Mrs Albert Victor',
 'Pears, Mr Edith',
 'Pelham, Mrs George',
 'Peñasco y castellana, Mr Maria Josefa Perezde Soto y Vallejo',
 'Perkis, Miss Walter John',
 'Perreault, Mr Mary Anne',
 'Perry, Mr Edgar Lionel',
 'Persson, Mr Ernst Ulrik',
 'Peters, Major William Chapman',
 'Peuchen, Mr Arthur Godfrey',
 'Pfropper, Mr Richard Paul Jozef',
 'Phillimore, Miss Harold Charles William',
 'Phillips, Miss Alice Frances Louisa',
 'Phillips, Mr Kate Florence',
 'Picard, Mrs Benoît',
 'Pinsky, Mr Rosa',
 'Pitman, Mr Herbert John',
 'Podesta, Mr Alfred John Alexander',
 'Poingdestre, Mr John Thomas',
 'Port, Mr Frank',
 'Portaluppi, Mrs Emilio Ilario Giuseppe',
 'Potter, Mr Lily Alexenia',
 'Prangnell, Mr George Alexander',
 'Prentice, Mrs Frank Winnold',
 'Prichard, Mr Alice Maud',
 'Priest, Mr Arthur John',
 'Prior, Mr Harold John Arnold',
 'Pugh, Mr Alfred',
 'Pusey, Mrs William Robert Holland',
 'Quick, Miss Jane',
 'Quick, Miss Winnifred Vera',
 'Quick, Mr Phyllis May',
 'Ranger, Mr Thomas',
 'Ray, Mrs Frederick Dent',
 'Renouf, Mrs Lillian',
 'Reynaldo, Mr Encarnación',
 'Rheims, Mr George Alexander Lucien',
 'Rice, Mrs Charles John',
 'Richards, Master Emily',
 'Richards, Master William Rowe',
 'Richards, Miss Sibley George',
 'Ridsdale, Miss Lucy',
 'Riordan, Mrs Hannah',
 'Robert, Mrs Elisabeth Walton',
 'Roberts, Mrs Mary Kezia',
 'Robinson, Mr Annie',
 'Romaine, Miss Charles Hallace',
 'Rosenbaum, Mr Edith Louise',
 'Ross, Miss Horace Leopold',
 'Roth, Mrs Sarah',
 'Rothes, Mr Lucy Noël Martha, Countess of',
 'Rothschild, Miss Elizabeth Jane Anne',
 'Rowe, Mr George Thomas',
 'Rugg, Mr Emily',
 'Rule, Mrs Samuel James',
 'Ryan, Miss Edward',
 'Ryerson, Miss Emily Maria',
 'Ryerson, Master Emily Borie',
 'Ryerson, Mr Susan Parker',
 'Ryerson, Mr John Borie',
 'Ryerson, Mlle William Edwy',
 'Saalfeld, Miss Adolphe',
 'Sägesser, Mr Emma',
 'Salkjelsvik, Mrs Anna Kristine',
 'Salomon, Miss Abraham Lincoln',
 'Sandström, Miss Agnes Charlotta',
 'Sandström, Mr Beatrice Irene',
 'Sandström, Mr Marguerite Rut',
 'Sap, Mr Julius',
 'Savage, Mrs Charles James',
 'Scarrott, Mr Joseph George',
 'Schabert, Mr Emma',
 'Scheerlinck, Mr Jean',
 'Scott, Mr Frederick William',
 'Self, Miss Albert Charles Edward',
 'Senior, Mr Harry',
 'Serreplaà, Mr Augusta Jeanne',
 'Seward, Mr Frederic Kimber',
 'Seward, Mrs Wilfred Deable',
 'Sheath, Mr Frederick',
 'Shelley, Miss Imanita Parrish',
 'Shiers, Mr Alfred Charles',
 'Shine, Miss Ellen',
 'Shulver, Miss Christopher Arthur',
 'Shutes, Mr Elizabeth Weed',
 'Silvén, Mrs Lyyli Karoliina',
 'Silverthorne, Mr Spencer Victor',
 'Silvey, Mr Alice Gray',
 'Simmons, Miss Andrew George James',
 'Simonius-blumer, Miss Colonel (Oberst) Alfons',
 'Sincock, Miss Maude',
 'Sinkkonen, Miss Anna',
 'Sjöblom, Miss Anna Sofia',
 'Slayter, Mrs Hilda Mary',
 'Sloan, Mr Mary Jane',
 'Slocombe, Mrs Maude Louise',
 'Sloper, Miss William Thompson',
 'Smith, Miss Mary Eloise',
 'Smith, Miss Marion',
 'Smith, Mr Kate Elizabeth',
 'Smyth, Mr Julia',
 'Snow, Mrs Eustace Philip',
 'Snyder, Mr John Pillsbury',
 'Snyder, Mr Nelle',
 'Sparkman, Mrs Henry William',
 'Spedden, Master Frederic Oakley',
 'Spedden, Mrs Margaretta Corning',
 'Spedden, Dr Robert Douglas',
 'Spencer, Miss Marie Eugenie',
 'Stähelin-maeglin, Miss Max',
 'Stanley, Mr Amy Zillah Elsie',
 'Stap, Mrs Sarah Agnes',
 'Stengel, Mrs Charles Emil Henry',
 'Stengel, Mr Annie May',
 'Stephenson, Mrs Martha',
 'Stewart, Mr John',
 'Stone, Mr Martha Evelyn',
 'Strandén, Mr Juho Niilosson',
 'Street, Mr Thomas Albert',
 'Sunderland, Mr Victor Francis',
 'Sundman, Mrs Johan Julian',
 'Svensson, Mr Johan Cervin',
 'Swift, Mrs Margaret Welles',
 'Symons, Master George Thomas Macdonald',
 'Tannūs, Mrs Thamīn',
 "Tannūs, Miss As'ad",
 'Taussig, Mr Tillie',
 'Taussig, Mrs Ruth',
 'Taylor, Mr Elmer Zebley',
 'Taylor, Mr Juliet Cummins',
 'Taylor, Mr George',
 'Taylor, Mr William Henry',
 'Tenglin, Mrs Gunnar Isidor',
 'Terrill, Mr Frank',
 'Thayer, Mr Marian Longstreth',
 'Thayer, Mr John Borland',
 'Theissinger, Mr Alfred',
 'Thomas, Mr Benjamin James',
 'Thomas, Miss Albert Charles',
 'Thompson, Mrs John William',
 'Thorne, Mr Gertrude Maybelle',
 'Thorneycroft, Mr Florence Kate',
 'Threlfall, Mr Thomas',
 'Thresher, Miss George Terrill',
 'Toms, Mr Fred',
 'Toomey, Mr Ellen Mary',
 'Törnqvist, Mrs Johan Vilhelm Henrik',
 'Triggs, Miss Robert',
 'Trout, Mrs Jessie Laird',
 'Troutt, Miss Edwina Celia',
 "Tu'mah, Master Hinnah",
 "Tu'mah, Mr Mariyam",
 "Tu'mah, Miss Jirjis Yūsuf",
 'Tucker, Mrs Gilbert Milligan jr',
 'Turja, Mr Anna Sofia',
 'Turkula, Mr Hedwig',
 'Vartanian, Miss David',
 'Vigott, Miss Philip Francis',
 "Wallcroft, Mr Ellen 'Nellie'",
 'Ward, Mrs Annie Moore',
 'Ward, Mrs William',
 'Ware, Mrs Florence Louise',
 'Warren, Miss Anna Sophia',
 'Watt, Miss Elizabeth',
 'Watt, Mr Robertha Josephine',
 'Webber, Mrs Susan',
 'Weikman, Mr Augustus Henry',
 'Weisz, Mrs Mathilde Françoise',
 'Weller, Miss William Clifford',
 'Wells, Master Addie Dart',
 'Wells, Mr Joan',
 'Wells, Mrs Ralph Lester',
 'Wennerström, Miss August',
 'West, Miss Ada Mary',
 'West, Mr Constance Miriam',
 'West, Mr Barbara Joyce',
 'Wheat, Mr Joseph Thomas',
 'Wheelton, Mrs Edenser Edward',
 'Whilems, Mr Charles',
 'White, Mr Ella Holmes',
 'White, Mr Alfred',
 'White, Mrs William George',
 'Whiteley, Miss Thomas Arthur',

Now let's get the persons from the task

In [9]:
data_folder = './source_data'
raw_train = pd.read_csv(path.join(data_folder, 'train.csv'), index_col='PassengerId').rename(str.lower, axis='columns')
raw_test = pd.read_csv(path.join(data_folder, 'test.csv'), index_col='PassengerId').rename(str.lower, axis='columns')
raw_train.index.names = raw_test.index.names = ['passengerid']
train_test = pd.concat([raw_train, raw_test])
train_test = train_test[['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']]
train_test = train_test.sort_values(by='name')
train_test.head(40)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,
846,3,"Abbing, Mr. Anthony",male,42.00,0,0,C.A. 5547,7.5500,NaN,S
1284,3,"Abbott, Master. Eugene Joseph",male,13.00,0,2,C.A. 2673,20.2500,NaN,S
747,3,"Abbott, Mr. Rossmore Edward",male,16.00,1,1,C.A. 2673,20.2500,NaN,S
280,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.00,1,1,C.A. 2673,20.2500,NaN,S
1237,3,"Abelseth, Miss. Karen Marie",female,16.00,0,0,348125,7.6500,NaN,S
949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.6500,F G63,S
309,2,"Abelson, Mr. Samuel",male,30.00,1,0,P/PP 3381,24.0000,NaN,C
875,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.00,1,0,P/PP 3381,24.0000,NaN,C
1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.00,0,0,SOTON/O2 3101284,7.9250,NaN,S
900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C
366,3,"Adahl, Mr. Mauritz Nils Martin",male,30.00,0,0,C 7076,7.2500,NaN,S
402,3,"Adams, Mr. John",male,26.00,0,0,341826,8.0500,NaN,S
41,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
856,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.00,0,1,392091,9.3500,NaN,S
208,3,"Albimona, Mr. Nassef Cassem",male,26.00,0,0,2699,18.7875,NaN,C
970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.0000,NaN,S
811,3,"Alexander, Mr. William",male,26.00,0,0,3474,7.8875,NaN,S
841,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.00,0,0,SOTON/O2 3101287,7.9250,NaN,S
211,3,"Ali, Mr. Ahmed",male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S
785,3,"Ali, Mr. William",male,25.00,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
731,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
5,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
306,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
298,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
1198,1,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
499,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
835,3,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S
1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.5250,NaN,S
193,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.00,1,0,350046,7.8542,NaN,S
461,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S
851,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
814,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S
120,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
69,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.7750,NaN,S
542,3,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S
543,3,"Andersson, Miss. Sigrid Elisabeth",female,11.00,4,2,347082,31.2750,NaN,S
14,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S
147,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,350043,7.7958,NaN,S

Now we can see that the names are different... No way. It looks like some other cheaters matched the names from site and names from task manually. No way.

Now we remember that my best score = 0.99760 despite the cheat. Also we know that there are 712 survived people totally according to info from https://www.encyclopedia-titanica.org/titanic-survivors/. Let's have a look to my cheat. How many people survived there?

In [11]:
cheat = pd.read_csv(path.join('./special_data', 'cheat.csv')).rename(str.lower, axis='columns')
cheat = cheat.sort_values(by='name')
cheat['survived'].sum()

500

Wow! Answer is much less then 712, however the accuracy is high...